<a href="https://colab.research.google.com/github/Ishansoni06/tuo/blob/main/machinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
print("hello , i am learning pytorch !!")

hello , i am learning pytorch !!


In [83]:
import torch
print(torch.__version__)

2.6.0+cu124


In [84]:
## Introduction to Tensor
## creating tensors


In [85]:
#scalar
scala = torch.tensor(7)
scala

tensor(7)

In [86]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [87]:
vector.ndim

1

In [88]:
#matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [89]:
matrix.shape

torch.Size([2, 2])

In [90]:
tensor = torch.tensor([[[7,9,8]]])
tensor.ndim

3

In [91]:
tensor.shape

torch.Size([1, 1, 3])

### Random Tensors

In [92]:
random_tensor = torch.rand(3,4)
random_tensor

TypeError: 'Tensor' object is not callable

In [ ]:
 ## a way to represnet any data is in the form of tensors
 ## we can describe an image with tensors too of size ([224 , 224 , 3]) height , width and color channels

In [ ]:
random_image_Size_tensor = torch.rand(size = (3,224,224))
random_image_Size_tensor.shape , random_image_Size_tensor.ndim

### Zeroes and Ones

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

### craeting range of tensors and tensors-like

In [ ]:
tensor = torch.arange(1,11)
tensor
hello = torch.arange(start = 1 , end = 11 , step = 1)
hello

In [ ]:
#creating tensor - like
ten_zeros = torch.zeros_like(input = hello)
ten_zeros


### tensor datatype

**note: ** tensor datatypes is one of the big three big erros you'll run into with pytorch & deeplearning

1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [ ]:
float32_tensor = torch.tensor([3.0,4.0,5.0] , dtype = None ,
                              device = None,
                              requires_grad=False)

In [ ]:
float32_tensor.dtype

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

In [ ]:
float16_tensor * float32_tensor

In [ ]:
int32_tensor = torch.tensor([3,6,9] , dtype = torch.long)
int32_tensor

In [ ]:
float32_tensor * int32_tensor

In [ ]:
### getting information from tensors

#1 . tensor not right datatype - to do get datatype from a tensor , can use tensor.dtype
#2 . tensors not right shape - to get shape from a tensor , can use tensor.shape
#3 . tensors not on the right device = to get device from a tensor , can use tensor.device


In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device tensor is on : {some_tensor.device}")

In [ ]:
### manipulating tensors ( tensor operation )

#tensor opeartion include
#1 . addition
#2 . subtraction
#3 . multiplication (element - wise)
#4 . division
#5 . matrix multiplication



In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

In [ ]:
tensor*10

In [ ]:
torch.mul(tensor,10)

In [ ]:
torch.matmul(tensor,tensor)

In [ ]:
%%time
value = 0
for i in range(len(tensor)) :
  value += tensor[i] * tensor[i]

print(value)

In [ ]:
%%time
torch.matmul(tensor,tensor)

In [ ]:
#shapes for tensor multiplication
tensor_A = torch.tensor ([[1,2] , [3,4] , [4,5]])
tensor_B = torch.tensor ([[7,8],[9,10],[11,12]])
# torch.matmul(tensor_A , tensor_B)
#torch.mm is shortfor matrix multiplication (alias)

In [ ]:
#to fix our tensor shape issues , we can manipulate the shape of one of our tensor susing transpose

tensor_B.T , tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A , tensor_B.T)

In [ ]:
#finding the min , max , mean , sum , etc (tensor aggregation)

x = torch.arange(0,100,10)
x

In [93]:
torch.min(x) , x.max()

(tensor(1), tensor(9))

In [94]:
torch.max(x) , x.min()

(tensor(9), tensor(1))

In [95]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean() # x wont work as it will give datatype error so i changed the datatype to float

(tensor(5.), tensor(5.))

In [96]:
## finding the positional min and max ( what position min and max occur )

x.argmin()

tensor(0)

In [97]:
x.argmax() # gives the index of max or min

tensor(8)

In [98]:
# reshaping stacking squeezing and unsqueezing

# reshaping  - reshapes an input tensor to a defined shape
# view - return
# stacking - combine multiple tensors on top of each ohter (vstack) or side by side (hstack)
# squeeze - removes all '1' dimensions form a tensor
# unsqueeze - add a '1' dimesion to a target tensor
# permute - return a view of the input with dimesions permuted (swapped) in a certain way


In [99]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [100]:
# add extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [101]:
#change the view
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
# changing z changes x ( because a view of a tensor shares the same memory as the original )
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [103]:
## indexing ( selecting data from tensors )
## indexing with pytorch is similar to indexing with numpy

In [104]:
# create a tensor
import torch
x = torch.arange

In [105]:
## indexing ( selcting data from tensors )

import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [106]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [107]:
x[0][1][0]

tensor(4)

In [108]:
# you can use ":" to select "all" of a target dimension
x[:,0,:]

tensor([[1, 2, 3]])

In [109]:
# get all values of 0th and 1st dimesion but only index 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [110]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

### PyTorch tensors and numpy

numpy is a popular scinetific python numerical computing library and because of this, Pytorch has funcationality to interact with it.

* Data in Numpy , want in pytorch tensor -> torch.from_numpy(ndarray)
*Pytorch tensor -> NumPy -> torch.tensor.numpy()




In [111]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning :- when coverting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [112]:
# default datatype of tensor is float32 and default datatype of numpy array is float 64

In [113]:
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
#tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor  , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
# change the tensor , what happens to 'numpy tensor'
tensor = tensor + 1 ;
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( trying to take random out of random )

in short how a neural network learns :

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ... '

to reduce the randomness in neural network and pytorch comes the concept of a **random seed**

essentially what the radom seed does is "flavor" the randomness

In [116]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

TypeError: 'Tensor' object is not callable

In [3]:
# let's make some random but reproducible tensors

import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tesor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tesor_D = torch.rand(3,4)

print(random_tesor_C)
print(random_tesor_D)
print(random_tesor_C == random_tesor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [5]:
## Running tensors and Pytorch objects on the GPUs ( and making faster computations )

## GPUs = faster computation on numbers , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory ( good )

In [1]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
#count number of devices
torch.cuda.device_count()

1

In [5]:
#create a tensor ( default on the CPU )
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# moce tensor to GPU ( if available )
tensor_on_GPU = tensor.to(device)
tensor_on_GPU


tensor([1, 2, 3], device='cuda:0')

### moving tensors back to the CPU

In [8]:
# if tensor is on GPU , can't transform it to NumPy
tensor_on_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
#to fix the GPU tensor with Numpy Issue , we can first set it to CPU
tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])